In [ ]:
#Question1.Demonstrate three different methods for creating identical 2D arrays in NumPy. Provide the code for each method and the final output after each method.

In [2]:
'''Answer1'''
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.asarray([[1, 2, 3], [4, 5, 6]])
array3 = np.asanyarray([[1, 2, 3], [4, 5, 6]])
print(array1)
print(array2)
print(array3)


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [3]:
#Question2. Using the Numpy function, generate an array of 100 evenly spaced numbers between 1 and 10 and
#Reshape that 1D array into a 2D array.

In [4]:
'''Answer2.'''
#Generate a 1D array of 100 evenly spaced numbers between 1 and 10
array_1d = np.linspace(1, 10, 100)

# Reshape the 1D array into a 2D array with 10 rows and 10 columns
array_2d = array_1d.reshape(10, 10)

print(array_2d)

[[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
   1.54545455  1.63636364  1.72727273  1.81818182]
 [ 1.90909091  2.          2.09090909  2.18181818  2.27272727  2.36363636
   2.45454545  2.54545455  2.63636364  2.72727273]
 [ 2.81818182  2.90909091  3.          3.09090909  3.18181818  3.27272727
   3.36363636  3.45454545  3.54545455  3.63636364]
 [ 3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
   4.27272727  4.36363636  4.45454545  4.54545455]
 [ 4.63636364  4.72727273  4.81818182  4.90909091  5.          5.09090909
   5.18181818  5.27272727  5.36363636  5.45454545]
 [ 5.54545455  5.63636364  5.72727273  5.81818182  5.90909091  6.
   6.09090909  6.18181818  6.27272727  6.36363636]
 [ 6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
   7.          7.09090909  7.18181818  7.27272727]
 [ 7.36363636  7.45454545  7.54545455  7.63636364  7.72727273  7.81818182
   7.90909091  8.          8.09090909  8.18181818]
 [ 8.272

In [5]:
#Question3.Explain the following terms:
#The difference in np.array, np.asarray and np.asanyarray.
# The difference between Deep copy and shallow copy.

In [6]:
'''Answer 3
np.array, np.asarray, and np.asanyarray

These three functions are used to create NumPy arrays from various input data types. They differ in their behavior and flexibility:

np.array(object, dtype=None, copy=True, order='K', subok=False):

This is the most general function for creating NumPy arrays.
It takes an object as input and converts it to a NumPy array.
It has several optional arguments:
dtype: Specifies the desired data type of the array.
copy: Controls whether to create a copy of the input data or reference the original data.
order: Specifies the memory layout of the array (C-contiguous or Fortran-contiguous).
subok: Determines whether to preserve the subclass of the input object.
np.asarray(a, dtype=None, order=None):

This function is similar to np.array, but it is more efficient for converting existing NumPy arrays or arrays from other libraries.
It does not have the copy or subok arguments.
np.asanyarray(a, dtype=None, order=None):

This function is even more efficient than np.asarray and tries to avoid creating a copy of the input data if possible.
It is suitable for cases where you are certain that the input data is already a NumPy array or can be converted without copying.
Deep Copy vs. Shallow Copy

When copying NumPy arrays, you can choose between deep copy and shallow copy.

Deep Copy:

Creates a new array with entirely new data.
Changes made to the original array will not affect the copy.
Use np.copy() to create a deep copy.
Shallow Copy:

Creates a new array that references the same data as the original array.
Changes made to the original array will also affect the copy.
Use np.array(original_array, copy=False) to create a shallow copy.
Choosing the Right Function

The choice between these functions depends on your specific use case and the nature of your input data. Here are some guidelines:

If you are unsure about the input data type or want to control the memory layout, use np.array.
If you know that the input data is already a NumPy array or from another library, use np.asarray or np.asanyarray for efficiency.
If you need to create a completely independent copy of the array, use a deep copy.
If you want to reference the same data but avoid unnecessary copying, use a shallow copy.
'''

"Answer 3\nnp.array, np.asarray, and np.asanyarray\n\nThese three functions are used to create NumPy arrays from various input data types. They differ in their behavior and flexibility:\n\nnp.array(object, dtype=None, copy=True, order='K', subok=False):\n\nThis is the most general function for creating NumPy arrays.\nIt takes an object as input and converts it to a NumPy array.\nIt has several optional arguments:\ndtype: Specifies the desired data type of the array.\ncopy: Controls whether to create a copy of the input data or reference the original data.\norder: Specifies the memory layout of the array (C-contiguous or Fortran-contiguous).\nsubok: Determines whether to preserve the subclass of the input object.\nnp.asarray(a, dtype=None, order=None):\n\nThis function is similar to np.array, but it is more efficient for converting existing NumPy arrays or arrays from other libraries.\nIt does not have the copy or subok arguments.\nnp.asanyarray(a, dtype=None, order=None):\n\nThis funct

In [7]:
#Question4.Generate a 3*3 array with random floating-point numbers between 5 and 20. Then, round each number in the array to 2 decimal places.

In [8]:
'''Answer4.'''
# Generate a 3x3 array with random floating-point numbers between 5 and 20
array = np.random.uniform(5, 20, (3, 3))

# Round each number to 2 decimal places
array_rounded = np.round(array, decimals=2)

print(array_rounded)

[[ 9.21 12.    6.39]
 [10.48 11.34 11.19]
 [10.49 18.67 14.3 ]]


In [9]:
# #Question5.Create a NumPy array with random integers Petween 1 and 10 of shape (5, 6). After creating the array perform the following operations:

#  a)Extract all even integers from array.

#  b)Extract all odd integers from array.

In [10]:
'''Answer5.'''
# Create a NumPy array with random integers between 1 and 10 of shape (5, 6)
array = np.random.randint(1, 11, (5, 6))

# Extract even integers from the array
even_integers = array[array % 2 == 0]

# Extract odd integers from the array
odd_integers = array[array % 2 != 0]

print("Array:")
print(array)
print("\nEven Integers:")
print(even_integers)
print("\nOdd Integers:")
print(odd_integers)

Array:
[[ 9 10  1  9  2  9]
 [10  4  2  6 10  1]
 [10 10  5  2 10  9]
 [ 7 10  5  3  5  8]
 [ 6  1  8  2  3  1]]

Even Integers:
[10  2 10  4  2  6 10 10 10  2 10 10  8  6  8  2]

Odd Integers:
[9 1 9 9 1 5 9 7 5 3 5 1 3 1]


In [11]:
#Question6.Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10. Perform the following operations:


#  a) Find the indices of the maximum values along each depth level (third axis).

#  b) Perform element-wise multiplication of between both array.

In [12]:
'''Answer6.'''
# Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10
array = np.random.randint(1, 11, (3, 3, 3))

# a) Find the indices of the maximum values along each depth level (third axis)
max_indices = np.argmax(array, axis=2)

# b) Perform element-wise multiplication of between both array
result = array * max_indices[..., np.newaxis]

print("Original array:")
print(array)
print("\nIndices of maximum values along each depth level:")
print(max_indices)
print("\nResult of element-wise multiplication:")
print(result)

Original array:
[[[ 3  8 10]
  [10  3  9]
  [ 1  5  1]]

 [[ 7  7  4]
  [ 4  6  5]
  [ 6  1  4]]

 [[ 3  4  6]
  [ 3  3  6]
  [ 6  3  4]]]

Indices of maximum values along each depth level:
[[2 0 1]
 [0 1 0]
 [2 2 0]]

Result of element-wise multiplication:
[[[ 6 16 20]
  [ 0  0  0]
  [ 1  5  1]]

 [[ 0  0  0]
  [ 4  6  5]
  [ 0  0  0]]

 [[ 6  8 12]
  [ 6  6 12]
  [ 0  0  0]]]


In [13]:
#Question7. Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and convert it to a numeric data type. Also display the table attributes and data types of each column.

In [17]:
'''Answer7.'''
import pandas as pd
df = pd.read_csv('People Data.csv')
df['Phone'] = df['Phone'].str.replace(r"[^\d]", "", regex=True)
df['Phone'] = pd.to_numeric(df['Phone'], errors='coerce')
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Index          1000 non-null   int64  
 1   User Id        1000 non-null   object 
 2   First Name     1000 non-null   object 
 3   Last Name      1000 non-null   object 
 4   Gender         1000 non-null   object 
 5   Email          1000 non-null   object 
 6   Phone          979 non-null    float64
 7   Date of birth  1000 non-null   object 
 8   Job Title      1000 non-null   object 
 9   Salary         1000 non-null   int64  
dtypes: float64(1), int64(2), object(7)
memory usage: 78.3+ KB
None


In [18]:
#Question8. Perform the following tasks using people dataset:

#  a) Read the 'data.csv' file using pandas, skipping the first 50 rows.

#  b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.

#  c) Display the first 10 rows of the filtered dataset.

#  d) Extract the ‘Salary’' column as a Series and display its last 5 values.

In [25]:
'''Answer8.'''
# a) Read data.csv, skipping the first 50 rows
df = pd.read_csv('People Data.csv', skiprows=50)

# b) Select specific columns
df1 = pd.read_csv("People Data.csv")
filtered_df = df1[['Last Name', 'Gender', 'Email', 'Phone', 'Salary']]

# c) Display the first 10 rows
print("First 10 rows of filtered data:")
print(filtered_df.head(10))

# d) Extract Salary column as Series and display last 5 values
salary_series = filtered_df['Salary']
print("\nLast 5 values of Salary:")
print(salary_series.tail(5))

First 10 rows of filtered data:
  Last Name  Gender                          Email               Phone  Salary
0   Mahoney    Male            pwarner@example.org        857.139.8239   90000
1    Rivers  Female  fergusonkatherine@example.net                 NaN   80000
2    Lowery  Female            fhoward@example.org       (599)782-0605   50000
3    Hooper    Male          zjohnston@example.com                 NaN   65000
4      Rice  Female               elin@example.net  (390)417-1635x3010  100000
5  Caldwell    Male          kaitlin13@example.net          8537800927   50000
6   Hoffman    Male         jeffharvey@example.com   093.655.7480x7895   60000
7  Andersen    Male           alicia33@example.org          4709522945   65000
8      Mays    Male             jake50@example.com        013.820.4758   50000
9  Mitchell    Male      lanechristina@example.net  (560)903-5068x4985   50000

Last 5 values of Salary:
995     90000
996     50000
997     60000
998    100000
999     90000
Nam

In [26]:
#Question9. Filter and select rows from the People_Dataset, where the “Last Name' column contains the name 'Duke', 'Gender' column contains the word Female and ‘Nalary’ should Pe less than 85000.

In [27]:
'''Answer9.'''
df = pd.read_csv("People Data.csv")
filtered_df = df[(df['Last Name'] == 'Duke') & (df['Gender'] == 'Female') & (df['Salary'] < 85000)]
print(filtered_df)

     Index          User Id First Name Last Name  Gender  \
45      46  99A502C175C4EBd     Olivia      Duke  Female   
210    211  DF17975CC0a0373    Katrina      Duke  Female   
457    458  dcE1B7DE83c1076      Traci      Duke  Female   
729    730  c9b482D7aa3e682     Lonnie      Duke  Female   

                        Email                   Phone Date of birth  \
45        diana26@example.net  001-366-475-8607x04350    13-10-1934   
210       robin78@example.com            740.434.0212    21-09-1935   
457  perryhoffman@example.org     +1-903-596-0995x489    11-02-1997   
729   kevinkramer@example.net            982.692.6257    12-05-2015   

           Job Title  Salary  
45           Dentist   60000  
210  Producer, radio   50000  
457        Herbalist   50000  
729     Nurse, adult   70000  


In [28]:
#Question 10. Create a 7*5 Dataframe in Pandas using a series generated from 35 random integers between 1 to 6?

In [29]:
'''Answer.10'''
# Generate a Series with 35 random integers between 1 and 6
series = pd.Series(np.random.randint(1, 7, 35))

# Create a DataFrame with 7 rows and 5 columns using the Series
df = pd.DataFrame(series.values.reshape(7, 5))

print(df)

   0  1  2  3  4
0  1  6  5  1  3
1  4  1  1  2  1
2  3  1  6  2  1
3  2  3  1  5  3
4  2  1  2  5  6
5  6  6  4  2  3
6  1  5  4  1  2


In [30]:
#Question11. Create two different Series, each of length 50, with the following criteria:

# a) The first Series should contain random numbers ranging from 10 to 50.

# b) The second Series should contain random numbers ranging from 100 to 1000.

# c) Create a DataFrame by 'oining these Series by column, and, change the names of the columns to 'col1', 'col2', etc...

In [31]:
'''Answer11.'''
# a) Create the first Series with random numbers from 10 to 50
series1 = pd.Series(np.random.randint(10, 51, 50))

# b) Create the second Series with random numbers from 100 to 1000
series2 = pd.Series(np.random.randint(100, 1001, 50))

# c) Create a DataFrame by joining the Series by column and changing column names
df = pd.concat([series1, series2], axis=1)
df.columns = ['col1', 'col2']

print(df)

    col1  col2
0     23   178
1     35   594
2     38   698
3     42   653
4     39   672
5     24   230
6     17   337
7     46   980
8     27   862
9     34   334
10    39   626
11    10   895
12    15   227
13    18   830
14    31   202
15    36   168
16    25   852
17    50   511
18    31   286
19    45   362
20    34   621
21    38   580
22    16   977
23    20   291
24    23   744
25    19   448
26    12   225
27    33   495
28    36   184
29    13   508
30    17   393
31    18   286
32    10   137
33    31   604
34    15   588
35    23   557
36    17   722
37    29   788
38    30   100
39    34   471
40    27   816
41    21   101
42    16   200
43    50   946
44    49   823
45    45   534
46    50   475
47    29   604
48    38   147
49    31   528


In [ ]:
#Question12.  Perform the following operations using people data set:

# a) Delete the 'Email', 'Phone', and 'Date of birth' columns from the dataset.

# b) Delete the rows containing any missing values.

# d) Print the final output also.

In [1]:
'''Answer 12.'''
import pandas as pd

# Load the dataset
df = pd.read_csv('People Data.csv')

# a) Delete the 'Email', 'Phone', and 'Date of birth' columns
df = df.drop(columns=['Email', 'Phone', 'Date of birth'])

# b) Delete rows containing missing values
df = df.dropna()

# Print the final output
print(df)

     Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000

In [ ]:
#Question13. Create two NumPy arrays, x and y, each containing 100 random float values between 0 and 1. Perform the
# following tasks using Matplotlib and NumPy:

# a) Create a scatter plot using x and y, setting the color of the points to red and the marker style to 'o'.

# b) Add a horizontal line at y = 0.5 using a dashed line style and label it as 'y = 0.5'.

# c) Add a vertical line at x = 0.5 using a dotted line style and label it as 'x = 0.5'.

# d) Label the x-axis as 'X-axis' and the y-axis as 'Y-axis'.

# e) Set the title of the plot as 'Advanced Scatter Plot of Random Values'.

# f) Display a legend for the scatter plot, the horizontal line, and the vertical line.

In [ ]:
'''Answer 13.'''
import numpy as np
import matplotlib.pyplot as plt

# Create two NumPy arrays with random float values between 0 and 1
x = np.random.rand(100)
y = np.random.rand(100)

# Create a scatter plot
plt.scatter(x, y, color='red', marker='o', label='Data Points')

# Add a horizontal line at y = 0.5
plt.axhline(y=0.5, color='green', linestyle='--', label='y = 0.5')

# Add a vertical line at x = 0.5
plt.axvline(x=0.5, color='blue', linestyle=':', label='x = 0.5')

# Set labels and title
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Advanced Scatter Plot of Random Values')

# Show the legend
plt.legend()

# Display the plot
plt.show()

In [ ]:
#Question14. Create a time-series dataset in a Pandas DataFrame with columns: 'Date', 'Temperature', 'Humidity' and Perform the following tasks using Matplotlib:
# a) Plot the 'Temperature' and 'Humidity' on the same plot with different y-axes (left y-axis for 'Temperature' and
# right y-axis for 'Humidity').

# b) Label the x-axis as 'Date'.

# c) Set the title of the plot as 'Temperature and Humidity Over Time'.

In [ ]:
'''Answer14'''
import pandas as pd
import matplotlib.pyplot as plt

# Create a time-series DataFrame
dates = pd.date_range(start='2023-01-01', periods=365)
temperature = np.random.randint(20, 40, size=365)
humidity = np.random.randint(50, 90, size=365)

df = pd.DataFrame({'Date': dates, 'Temperature': temperature, 'Humidity': humidity})

# Create a figure with two subplots
fig, ax1 = plt.subplots()

# Plot 'Temperature' on the left y-axis
ax1.plot(df['Date'], df['Temperature'], color='blue', label='Temperature')
ax1.set_xlabel('Date')
ax1.set_ylabel('Temperature (Celsius)', color='blue')

# Create a second axis for 'Humidity'
ax2 = ax1.twinx()

# Plot 'Humidity' on the right y-axis
ax2.plot(df['Date'], df['Humidity'], color='red', label='Humidity')
ax2.set_ylabel('Humidity (%)', color='red')

# Set the title
plt.title('Temperature and Humidity Over Time')

# Show the legend
plt.legend()

# Display the plot
plt.tight_layout()
plt.show()

In [ ]:
#Question15. Create a NumPy array data containing 1000 samples from a normal distribution. Perform the following tasks using Matplotlib:
# a) Plot a histogram of the data with 30 bins.

# b) Overlay a line plot representing the normal distribution's probability density function (PDF).

# c) Label the x-axis as 'Value' and the y-axis as 'Frequency/Probability'.

# d) Set the title of the plot as 'Histogram with PDF Overlay'.

In [3]:
pip install scipy

   ---------------------------------------- 0.0/44.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/44.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/44.5 MB ? eta -:--:--
   ---------------------------------------- 0.5/44.5 MB 645.7 kB/s eta 0:01:09
    --------------------------------------- 0.8/44.5 MB 884.1 kB/s eta 0:00:50
   - -------------------------------------- 1.3/44.5 MB 1.2 MB/s eta 0:00:35
   - -------------------------------------- 1.8/44.5 MB 1.4 MB/s eta 0:00:30
   - -------------------------------------- 2.1/44.5 MB 1.5 MB/s eta 0:00:29
   -- ------------------------------------- 2.4/44.5 MB 1.4 MB/s eta 0:00:30
   -- ------------------------------------- 3.1/44.5 MB 1.6 MB/s eta 0:00:26
   --- ------------------------------------ 3.4/44.5 MB 1.7 MB/s eta 0:00:25
   --- ------------------------------------ 3.9/44.5 MB 1.7 MB/s eta 0:00:25
   --- ------------------------------------ 4.2/44.5 MB 1.6 MB/s eta 0:00:26
   ---- --------

In [ ]:
'''Answer15.'''
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Create a NumPy array with 1000 samples from a normal distribution
data = np.random.normal(loc=0, scale=1, size=1000)

# Create a histogram with 30 bins
plt.hist(data, bins=30, density=True, alpha=0.6, label='Histogram')

# Calculate the mean and standard deviation of the data
mean, std = np.mean(data), np.std(data)

# Create an array of x values for the PDF
x = np.linspace(min(data), max(data), 100)

# Calculate the PDF values
pdf = norm.pdf(x, loc=mean, scale=std)

# Plot the PDF as a line
plt.plot(x, pdf, color='red', label='PDF')

# Set labels and title
plt.xlabel('Value')
plt.ylabel('Frequency/Probability')
plt.title('Histogram with PDF Overlay')

# Show the legend
plt.legend()

# Display the plot
plt.show()

In [ ]:
#Question16. Set the title of the plot as 'Histogram with PDF Overlay'.

In [ ]:
'''Answer16.'''
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Create a NumPy array with 1000 samples from a normal distribution
data = np.random.normal(loc=0, scale=1, size=1000)

# Create a histogram with 30 bins
plt.hist(data, bins=30, density=True, alpha=0.6, label='Histogram')

# Calculate the mean and standard deviation of the data
mean, std = np.mean(data), np.std(data)

# Create an array of x values for the PDF
x = np.linspace(min(data), max(data), 100)

# Calculate the PDF values
pdf = norm.pdf(x, loc=mean, scale=std)

# Plot the PDF as a line
plt.plot(x, pdf, color='red', label='PDF')

# Set labels and title
plt.xlabel('Value')
plt.ylabel('Frequency/Probability')
plt.title('Histogram with PDF Overlay')

# Show the legend
plt.legend()

# Display the plot
plt.show()

In [ ]:
#Question17. Create a Seaborn scatter plot of two random arrays, color points based on their position relative to the origin (quadrants), add a legend, label the axes, and set the title as 'Quadrant-wise Scatter Plot'.

In [ ]:
'''Answer17.'''
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Generate two random arrays
x = np.random.randn(1000)
y = np.random.randn(1000)

# Create a DataFrame with x and y values
df = pd.DataFrame({'x': x, 'y': y})

# Determine the quadrant for each point
df['quadrant'] = np.where(df['x'] >= 0,
                         np.where(df['y'] >= 0, 'I', 'IV'),
                         np.where(df['y'] >= 0, 'II', 'III'))

# Create a scatter plot with points colored by quadrant
sns.scatterplot(data=df, x='x', y='y', hue='quadrant', palette='colorblind')

# Add a legend
plt.legend(title='Quadrant')

# Label the axes
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

# Set the title
plt.title('Quadrant-wise Scatter Plot')

# Display the plot
plt.show()

In [ ]:
#Question18. With Bokeh, plot a line chart of a sine wave function, add grid lines, label the axes, and set the title as 'Sine Wave Function'.

In [ ]:
'''Answer18.'''
import numpy as np
from bokeh.plotting import figure, output_file, show

# Generate x and y values for the sine wave
x = np.linspace(0, 2 * np.pi, 1000)
y = np.sin(x)

# Create a Bokeh figure
p = figure(title='Sine Wave Function', x_axis_label='x', y_axis_label='y')

# Add a line plot of the sine wave
p.line(x, y, color='blue', line_width=2)

# Add grid lines
p.grid(grid_line_color='gray', grid_line_alpha=0.2)

# Show the plot
show(p)

In [ ]:
#Question19. Using Bokeh, generate a bar chart of randomly generated categorical data, color bars based on their values, add hover tooltips to display exact values, label the axes, and set the title as 'Random Categorical Bar Chart'.

In [ ]:
'''Answer19.'''
import numpy as np
import pandas as pd
from bokeh.plotting import figure, output_file, show
from bokeh.models import HoverTool

# Generate random categorical data
categories = ['A', 'B', 'C', 'D', 'E']
values = np.random.randint(10, 30, size=5)

# Create a DataFrame
df = pd.DataFrame({'Category': categories, 'Value': values})

# Create a Bokeh figure
p = figure(title='Random Categorical Bar Chart', x_axis_label='Category', y_axis_label='Value')

# Create a bar chart with color based on values
p.vbar(x=df['Category'], top=df['Value'], width=0.5, color='Viridis256', alpha=0.8)

# Add hover tooltips to display exact values
hover = HoverTool(tooltips=[('Category', '@Category'), ('Value', '@Value')])
p.add_tools(hover)

# Show the plot
show(p)

In [ ]:
#Question20. Using Plotly, create a basic line plot of a randomly generated dataset, label the axes, and set the title as 'Simple Line Plot'.

In [ ]:
'''Answer20.'''
import plotly.graph_objects as go
import numpy as np

# Generate random data
x = np.linspace(0, 10, 100)
y = np.random.randn(100)

# Create a figure
fig = go.Figure()

# Add a trace
fig.add_trace(go.Scatter(x=x, y=y, mode='lines'))

# Set title and labels
fig.update_layout(title='Simple Line Plot', xaxis_title='X-axis', yaxis_title='Y-axis')

# Show the plot
fig.show()

In [ ]:
#Question21. Using Plotly, create an interactive pie chart of randomly generated data, add labels and percentages, set the title as 'Interactive Pie Chart'.

In [ ]:
'''Answer21.'''
import plotly.graph_objects as go
import numpy as np

# Generate random data
labels = ['A', 'B', 'C', 'D', 'E']
values = np.random.randint(10, 30, size=5)

# Create a figure
fig = go.Figure(data=[go.Pie(labels=labels, values=values)])

# Set title and labels
fig.update_layout(title='Interactive Pie Chart')

# Show the plot
fig.show()